// PlaceIQ Backend In-Memory Database Store

export const usersDB = [
  {
    id: 'std_01',
    role: 'student',
    name: 'Aarav Sharma',
    email: 'aarav.sharma22@vitstudent.ac.in',
    college: 'Vellore Institute of Technology (VIT)',
    degree: 'B.Tech - Computer Science & Engineering',
    graduationYear: 2026,
    cgpa: 8.85,
    placementReadinessScore: 84,
    streakDays: 14,
    xpPoints: 3420,
    batchRank: 12,
    totalBatchStudents: 420,
    targetCompanies: ['Amazon', 'Flipkart', 'TCS Digital', 'Infosys DSE'],
  },
  {
    id: 'faculty_01',
    role: 'trainer',
    name: 'Prof. Rajesh K. Sundaram',
    email: 'rajesh.sundaram@vit.ac.in',
    designation: 'Head of Technical Training & Competitive Coding',
    department: 'School of Computer Science & Engineering',
    college: 'Vellore Institute of Technology (VIT)',
    batchesAssigned: ['2026 CSE Batch A', '2026 CSE Batch B', '2026 AI-DS Batch'],
  },
  {
    id: 'tpo_01',
    role: 'admin',
    name: 'Dr. Meenakshi Ramanathan',
    email: 'tpo.director@vit.ac.in',
    designation: 'Chief Training & Placement Officer (TPO)',
    college: 'Vellore Institute of Technology (VIT)',
    campusPlacementStats: {
      totalRegistered: 1850,
      placedStudents: 1320,
      placementRate: '71.35%',
      highestCTC: '44.5 LPA (Amazon)',
      averageCTC: '9.2 LPA',
      companiesVisited: 74,
      upcomingDrives: 12,
    },
  },
];

export const drivesDB = [
  {
    id: 'drive_01',
    company: 'Amazon India',
    tier: 'Tier 1 Product',
    logo: '🛒',
    role: 'Software Development Engineer 1 (SDE-1)',
    packageCTC: '44.5 LPA',
    baseSalary: '16.5 LPA',
    location: 'Bengaluru / Hyderabad',
    minCGPA: 7.5,
    eligibleBranches: ['CSE', 'IT', 'ECE', 'AI-DS'],
    date: '2026-10-22',
    status: 'Applications Open',
    applied: true,
    applicationStage: 'OA Shortlisted',
  },
  {
    id: 'drive_02',
    company: 'Tata Consultancy Services (TCS)',
    tier: 'Mass Recruiter / IT Services',
    logo: '🏢',
    role: 'TCS Digital (7.5 LPA) & TCS Ninja (3.6 LPA)',
    packageCTC: '7.5 LPA / 3.6 LPA',
    baseSalary: '7.0 LPA',
    location: 'Pan India',
    minCGPA: 6.0,
    eligibleBranches: ['All Engineering Branches'],
    date: '2026-10-28',
    status: 'Registration Closing Soon',
    applied: true,
    applicationStage: 'Registered',
  },
];

export const doubtsDB = [
  {
    id: 'd1',
    studentName: 'Aarav Sharma',
    regNo: '22BCE1042',
    batch: '2026 CSE Batch A',
    topic: 'Dynamic Programming - 0/1 Knapsack Space Optimization',
    question: 'Prof. Sundaram, in the bottom-up DP table for 0/1 Knapsack, why can we iterate backwards when reducing 2D space to 1D array?',
    timeAgo: '15 mins ago',
    status: 'pending',
    companyTarget: 'Amazon SDE-1',
  },
];
